main/urls.py
from django.urls import path
from main.views import (show_main, create_item, 
                        show_xml, show_json, 
                        show_xml_by_id, show_json_by_id, 
                        register, login_user,
                        logout_user, delete_item, add_item, subtract_item,
                        get_product_json, add_product_ajax, delete_product_ajax, update_product_qty_ajax,
                        create_product_flutter, show_json_user
                        )

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete_item/<int:item_id>/', delete_item, name='delete_item'),
    path('add_item/<int:item_id>/', add_item, name='add_item'),
    path('subtract_item/<int:item_id>/', subtract_item, name='subtract_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_product_ajax/', delete_product_ajax, name='delete_product_ajax'),
    path('update_product_qty_ajax/', update_product_qty_ajax, name='update_product_qty_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json-user/<str:uname>/', show_json_user, name='show_json_user'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

poke_co/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    rarities = (
        ("Common",'Common'),
        ("Rare",'Rare'),
        ("Epic",'Epic'),
        ("Legendary",'Legendary'),
        ('Unknown','Unknown')
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, name="name")
    amount = models.IntegerField(name="amount")
    rarity = models.CharField(name="rarity", choices=rarities, default='Unknown',max_length=10)
    power = models.IntegerField(name="power", max_length=3)
    description = models.TextField(name="description")
    date_added = models.DateTimeField(name='date_added',auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "rarity", "power", "description"]

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.core import serializers
from main.forms import ProductForm
from django.urls import reverse
from main.models import Item
from django.db.models import Sum
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt 
import datetime
import json
from django.http import JsonResponse


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    total_characters = Item.objects.filter(user=request.user).count() or 0
    total_pokemon = Item.objects.filter(user=request.user).aggregate(total_amount=Sum('amount'))['total_amount'] or 0
    items = Item.objects.filter(user=request.user)
    context = {
        'name':request.user.username,
        'class':'PBP-B',
        'char_name':'Pikachu',
        'char_description':'Pikachu, the most popular character.',
        'char_rarity':'Rare',
        'total_characters':total_characters,
        'total_pokemon':total_pokemon,
        'items':items,
        'last_login':request.COOKIES['last_login']
    }

    return render(request, 'main.html', context)

def create_item(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    item.delete()
    return redirect('main:show_main')

def add_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    item.amount += 1
    item.save()
    return redirect('main:show_main')

def subtract_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    item.amount = max(1, item.amount - 1)
    item.save()
    return redirect('main:show_main')

def max(a, b):
    if a > b:
        return a
    return b

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def update_product_qty_ajax(request):
    if request.method == 'PUT':
        data = json.loads(request.body)
        product_id = data.get('character_id')
        product = Item.objects.get(pk=product_id)
        if data.get("modify") == "increment": 
            product.amount += 1
        if data.get("modify") == "decrement":
            product.amount = max(1, product.amount - 1)
        product.save()

        return HttpResponse(b"OK", status=200)

    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request):
    if request.method == 'DELETE':
        product_id = json.loads(request.body).get('character_id')
        product = Item.objects.get(pk=product_id)
        product.delete()

        return HttpResponse(b"OK", status=200)

    return HttpResponseNotFound()

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        rarity = request.POST.get("rarity")
        power = request.POST.get("power")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, 
                           amount=amount, 
                           rarity=rarity,
                           power=power,
                           description=description, 
                           user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = data["amount"],
            rarity = data["rarity"],
            power = data["power"],
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

@csrf_exempt
def show_json_user(request, uname):
    data_item = Item.objects.all()

    for data in data_item:
        if data.user.username == uname:
            user_id = data.user
            data = Item.objects.filter(user = user_id)
            break
        else:
            data = []
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/create_item.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}
    <title>Add New Character</title>
    <link rel="stylesheet" href="{% static 'main/css/create_item.css' %}">
    <style>
        body{
            background-image: url("{% static '/main/assets/poke-ball.png' %}");
            background-position: center;
        }
    </style>
{% endblock meta %}

{% block content %}

    <section class="add_item">
        <h1>Add New Character to Your List</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Add Character"/>
                    </td>
                </tr>
            </table>
        </form>
    </section>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}

    <title>Login</title>
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <style>
        .login{
            background-image: url("{% static 'main/assets/big-wallpaper.jpg' %}");
            background-position: center;
            background-size: cover;
        }
    </style>

{% endblock meta %}

{% block content %}

    <div class="login">
        <img src="{% static 'main\assets\pokemon-logo.png' %}" alt="logo" class="logo" style="padding: 0;">
        <div class="login-container">
            <h1>Login</h1>

            <form method="POST" action="">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Username">

                <label for="password">Password:</label>
                <input type="password" name="password" placeholder="Password">

                <input class="btn" type="submit" value="Login">
            </form>

            {% if messages %}
                <div class="error">
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <p>Don't have an account yet? <a href="{% url 'main:register' %}"><br>Register Now</a></p>
        </div>
    </div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poké.co</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% endblock meta %}

{% block content %}
    <body>
        <header>
            <h1>Welcome to Poké.co</h1>
            <p>A Pokémon character-collecting game</p>
        </header>

        <section>
            <h2>Player Information</h2>
            <h5>Name:</h5>
            <p>{{ name }}</p>
            <h5>Class:</h5>
            <p>{{ class }}</p>
            <h5>Last Login:</h5>
            <p>{{ last_login }}</p>
            <a href="{% url 'main:logout' %}">
                <button>
                    Logout
                </button>
            </a>
        </section>

        <section>
            <h2>Featured Character</h2>
            <p>Pikachu</p>
            <img src="{% static 'main/assets/Angry-Pikachu-Transparent.png' %}" alt="Pikachu">
        </section>

        <section>
            <h2>Featured Character Information</h2>
            <h5>Name:</h5>
            <p>{{ char_name }}</p>
            <h5>Rarity:</h5>
            <p>{{ char_rarity }}</p>
            <h5>Description:</h5>
            <p>{{ char_description }}</p>
        </section>

        <!-- The item card section -->
        <section id="item_cards"></section> 

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Character</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="rarity" class="col-form-label">Rarity:</label>
                                <select class="form-select" id="rarity" name="rarity">
                                    <option value="Unknown">Unknown</option>
                                    <option value="Common">Common</option>
                                    <option value="Rare">Rare</option>
                                    <option value="Epic">Epic</option>
                                    <option value="Legendary">Legendary</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="power" class="col-form-label">Power:</label>
                                <input type="number" class="form-control" id="power" name="power"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Character</button>
                    </div>
                </div>
            </div>
        </div>

        <footer>
            <p>@ 2023 Fadhil Muhammad (2206083464). Pemrograman Berbasis Platform - Gasal 23/24.</p>
        </footer>
    </body>

    <script>
        /*DELETE Method*/
        function deleteProduct(id) {
            fetch("{% url 'main:delete_product_ajax' %}", {
                method: "DELETE",
                body: JSON.stringify({
                    "character_id":id
                })
            }).then(refreshProducts)
        }

        /*PUT Method*/
        function updateProductQty(id, modify){
            fetch("{% url 'main:update_product_qty_ajax' %}", {
                method: "PUT",
                body: JSON.stringify({
                    "character_id":id,
                    "modify":modify
                })
            }).then(refreshProducts)
        }

        /*POST Method*/
        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }
        
        /*GET Method*/
        async function getItems() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            document.getElementById("item_cards").innerHTML = ""

            const Items = await getItems()
            let total_characters = Items.length
            let total_pokemon = 0
            Items.forEach((item) => {
                total_pokemon += item.fields.amount
            })

            let htmlString = `\n
            <h2>Your Collections</h2>
            <p id="qty-text">You currently own a total of ${total_characters} characters and a total of ${total_pokemon} Pokémons</p>
            <div style="display: flex; flex-wrap: wrap;" id="collection_cards">\n
            `
            
            Items.forEach((item) => {
                let deleteItemURL = `{% url 'main:delete_item' 0 %}`.replace("0", item.pk)
                let addItemURL = `{% url 'main:add_item' 0 %}`.replace("0", item.pk)
                let subtractItemURL = `{% url 'main:subtract_item' 0 %}`.replace("0", item.pk)
                htmlString += `\n
                <div class="card" id="item-${item.pk}">
                    <div class="card-header">
                        <a>
                            <button id="button_delete" data-item-pk=${item.pk}>delete</button>
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="card-title">${item.fields.name}</div>
                        <div class="card-info">
                            <p>Date Added (UTC+7): ${item.fields.date_added}</p><br>
                            <p>Amount: ${item.fields.amount}</p><br>
                            <p>Rarity: ${item.fields.rarity}</p><br>
                            <p>Power: ${item.fields.power}</p><br>
                        </div>
                        <div class="card-description">${item.fields.description}</div>
                    </div>
                    <div class="card-footer">
                        <a>
                            <button id="modify-qty" data-modifier="increment" data-item-pk=${item.pk}>+</button>
                        </a>
                        <p style="display: inline-block; margin: 0 10px;">${item.fields.amount}</p>
                        <a>
                            <button id="modify-qty" data-modifier="decrement" data-item-pk=${item.pk}>-</button>
                        </a>
                    </div>
                </div>`;
            })
            
            htmlString += `\n
            </div>
            <a href="{% url 'main:create_item' %}">
                <button>
                    Add New Character
                </button>
            </a>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add New Character by AJAX
            </button>
            `

            document.getElementById("item_cards").innerHTML = htmlString
            document.querySelectorAll('#button_delete').forEach(function(button) {
                button.addEventListener('click', function() {
                    let itemPK = this.getAttribute('data-item-pk');
                    deleteProduct(itemPK);
                });
            });

            document.querySelectorAll("#modify-qty").forEach(function(button) {
                button.addEventListener('click', function() {
                    let itemPK = this.getAttribute("data-item-pk")
                    let modifier = this.getAttribute("data-modifier")
                    updateProductQty(itemPK, modifier)
                })
            })
            

            let x = document.querySelectorAll(".card")
            x[x.length - 1].style = "background-color: black; color: white;"

            x = document.querySelectorAll(".card-header")
            x[x.length - 1].style = "background-color: red;"
            
            x = document.querySelectorAll(".card-footer")
            x[x.length - 1].style = "background-color: orange; color: black; border: 1px solid black"
        }
        
        document.getElementById("button_add").onclick = addProduct
        refreshProducts()
    </script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

    <title>Register</title>
    <link rel="stylesheet" href="{% static 'main/css/register.css' %}">
    <style>
        .register{
            background-image: url("{% static 'main/assets/regist-background.jpg' %}");
            background-position: center;
            background-size: cover;
        }
    </style>

{% endblock meta %}

{% block content %}

    <section class = "register">
        <div class = "register-container">
            <h1>Register</h1>  

                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input type="submit" name="submit" value="Register"/></td>  
                        </tr>  
                    </table>  
                </form>

            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                    {% endfor %}  
                </ul>   
            {% endif %}
        </div>
    </section>  

{% endblock content %}